nomenclature:
  name: student_profile
  verboseName: Student Profile
description: A student's personal profile page
baseUrls:
  http: student_profile/
  ws: student_profile/
acceptables:
  roles:
    - name: Student
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
isApi: true
