nomenclature:
  name: student_profile
  verboseName: StudentProfile
baseUrls:
  http: student_profile/
  ws: student_profile/
acceptables:
  roles:
  - name: Student
    activeStatuses:
    - IS_ACTIVE
    - HAS_BEEN_ACTIVE
isApi: true
